sudo: required

services:
  - docker

before_install:
  - docker build -t kevinmitaki/complex-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kevinmitaki/complex-react-test npm test

after_success:
  - docker build -t kevinmitaki/complex-client ./client
  - docker build -t kevinmitaki/complex-nginx ./nginx
  - docker build -t kevinmitaki/complex-server ./server
  - docker build -t kevinmitaki/complex-worker ./worker

  # LOG IN TO THE DOCKER CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # PUSH IMAGES TO DOCKER HUB
  - docker push kevinmitaki/complex-client
  - docker push kevinmitaki/complex-nginx
  - docker push kevinmitaki/complex-server
  - docker push kevinmitaki/complex-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: complex
  env: Complex-env
  bucket_name: elasticbeanstalk-eu-west-2-717469761592
  bucket_path: complex
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
