apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: kevinmitaki/complex-server
          ports:
            - containerPort: 5000
          env:
            - name: PG_HOST
              value:
            - name: PG_PORT
              value:
            - name: POSTGRES_PASSWORD
              value:
            - name: PG_DATABASE
              value:
            - name: PG_USER
              value:
            - name: REDIS_HOST
              value:
            - name: REDIS_PORT
              value:
